apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chilly-skunk-python
  janus-idp.io/tekton: chilly-skunk-python
  backstage.io/kubernetes-id: chilly-skunk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chilly-skunk-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
